### PR TITLE
Add Project Director Role Description

### PR DESCRIPTION
**Pull request by eholk**
This was pulled out of PR #12 so we can land the two separately.

### CODE REVIEW

**Comment by eholk** [comment]
> What's the process for resolving the TODOs?

Good question! I think we can probably just remove them and put this PR up to a poll from the Council. (I'm also not sure whether this needs Council approval, or if we can just delegate it all to the Project Director Elections Committee instead?)

**Comment by eholk** [comment]
@rust-lang/leadership-council - We haven't had any substantial edits on this in a while. I think we should go ahead and merge this one. 

I think going forward I'd like to add more clarifications (for example, how we interpret affiliation limits and other eligibility requirements and expectations) but given that we are going through the election process right now I'd rather not be changing these things in flight.

@rfcbot merge

**Comment by eholk** [comment]
@rfcbot pr merge

**Review by ehuss — APPROVED** [review]
Thanks!

**Pull request merged**
