### PR TITLE
Do not video/audio record council meetings

### PR DESCRIPTION
**Pull request by traviscross**
We have not been getting meaningful value out of making these recordings, and there are certain drawbacks to making them, so let's stop making video and audio recordings of the council meetings.

### CODE REVIEW

**Comment by BurntSushi** [comment]
I can make some guesses to this, but:

> and there are certain drawbacks to making them

Could y'all flesh this out a bit more? It's very vague and having something concrete written down would be helpful I think.

**Comment by ehuss** [comment]
@rfcbot concern expand-on-drawbacks

Just to ensure this gets addressed before merging.

https://github.com/rust-lang/leadership-council/pull/102#issuecomment-2402468510

**Comment by traviscross** [comment]
We make recordings that we don't intend to publish.  We don't use these recordings for any meaningful purpose.  So we are getting near-zero value out of making these.

But recording something and storing it, even for a short period of time, increases greatly the risk that thing will be disclosed (either publicly or to some particular party), or that it may end up stored for longer than we intend.

The [revealed preference](https://en.wikipedia.org/wiki/Revealed_preference) of our existing decision to not publish these recordings is that we must anticipate certain possible negative risks or effects of their disclosure.  That is, if we thought it better to publish these, we'd already be doing so.

But in making these recordings at all, we're running some risk of that disclosure.  Certainly we're running a greater risk than if we don't make these recordings at all.  And we're getting near-zero value in return for that risk.

Security risks often come from expectations being violated.  If we speak assuming that what we say will not have a recording of it published -- and then it is -- that's worse in expectation than if we knew that the recordings would be published, as then we would always speak with that in mind.

For me, this is a clear call on that basis, and on the basis that we're not getting value out of these, so I don't particularly feel the need to enumerate all of the drawbacks that might accrue due to unexpected disclosure.  Certainly there are some I can imagine, but I'd prefer to not speculate too much.

**Comment by traviscross** [comment]
Also of note, doing these recordings is a constant minor hassle during the meetings, and managing them is work for the people on the council that do that.  That hassle and work should be offset by some non-trivial benefit that seems missing here.

**Comment by traviscross** [comment]
Let's leave this nominated for tomorrow to talk through the concern and whether there's anything more we want to write down here.  Perhaps in the meeting we could add some color around this.

I'd expect this to take 5-10 minutes.

**Comment by BurntSushi** [comment]
Thank you! I think this in particular resonates with me personally:

> If we speak assuming that what we say will not have a recording of it published -- and then it is -- that's worse in expectation than if we knew that the recordings would be published, as then we would always speak with that in mind.

**Comment by ehuss** [comment]
@rfcbot resolve expand-on-drawbacks

**Comment by ehuss** [comment]
@rfcbot resolve expand-on-drawbacks

**Comment by traviscross** [comment]
We discussed this in the meeting briefly today for visibility and to confirm that all were happy with our statement of reasons here.  No objections were raised, and the concern here has now been resolved, so this is in FCP.

**Review by ehuss — APPROVED** [review]

**Pull request merged**
